test: test workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -126,7 +126,7 @@ jobs:
           kubectl apply -f testing/scheduler/scheduler_job.yaml
           sleep 5
 
-      - name: Test scheduler processing
+      - name: Test scheduler for pvc1
         run: |
           if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc1 from namespace anray-liu"; then
               echo "Scheduler didn't find pvc1. Test failed."
@@ -134,6 +134,20 @@ jobs:
           else
               if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc1 from namespace anray-liu" -A 3 | grep "Grace period not passed. Skipping"; then
                   echo "Scheduler didn't skip pvc1. Test failed."
+                  exit 2
+              else
+                  echo "Test passed."
+              fi
+          fi
+
+      - name: Test scheduler for pvc2
+        run: |
+          if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc2 from namespace anray-liu"; then
+              echo "Scheduler didn't find pvc2. Test failed."
+              exit 2
+          else
+              if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc2 from namespace anray-liu" -A 1 | grep "Not labelled. Skipping."; then
+                  echo "Scheduler didn't skip pvc2. Test failed."
                   exit 2
               else
                   echo "Test passed."
