test: test workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -70,13 +70,13 @@ jobs:
               exit 2
           else 
               echo "Test passed."
-              # OUTPUT="${kubectl get pvc pvc1 -n anray-liu | grep labels -A 1}"
-              # if [[ "${OUTPUT}" = "volume-cleaner/unattached-time:"* ]]; then
-              #     echo "Test passed."
-              # else
-              #     echo "Wrong label found. Test failed."
-              #     exit 1
-              # fi
+              OUTPUT="${kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels -A 1}"
+              if [[ "${OUTPUT}" = "volume-cleaner/unattached-time:"* ]]; then
+                  echo "Test passed."
+              else
+                  echo "Wrong label found. Test failed."
+                  exit 1
+              fi
           fi
 
       - name: Print logs
