feat(cicd): add integration tests (#98)
This PR adds integration tests to the ci workflow. It works by creating a local kind cluster, running the controller and scheduler in that cluster, and then using bash to check the logs. If the wrong logs are outputted, the job echoes an error and terminates.
---------

Co-authored-by: Justin Zhang <jing.justin@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -32,7 +32,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   test:
-    name: Golang Tests
+    name: Unit Tests
     runs-on: ubuntu-latest
     steps:
       # allows workflow to access the repo
@@ -123,3 +123,156 @@ jobs:
     with:
       verticals: ${{needs.filter.outputs.images}}
     secrets: inherit
+
+  # creates a local cluster and tests for correct behaviour
+  integration-test:
+    name: Integration Tests
+    runs-on: ubuntu-latest
+    steps:
+      # allows workflow to access the repo
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install Kind
+        uses: helm/kind-action@v1
+        with:
+          registry: true
+          registry_port: 5050
+
+      - name: Create Kind cluster
+        run: kind create cluster
+
+      - name: Build docker files
+        run: |
+          docker build --progress=plain --no-cache -t localhost:5050/controller:test -f testing/controller/Dockerfile ..
+          docker build --progress=plain --no-cache -t localhost:5050/scheduler:test -f testing/scheduler/Dockerfile ..
+
+      - name: Push docker files to Kind cluster
+        run: |
+          docker push localhost:5050/controller:test
+          docker push localhost:5050/scheduler:test
+          kind load docker-image localhost:5050/controller:test
+          kind load docker-image localhost:5050/scheduler:test
+
+      - name: Apply cluster resources
+        run: kubectl apply -f testing/manifests.yaml
+
+      - name: Apply helper resources
+        run: |
+          kubectl apply -f manifests/rbac.yaml \
+            -f manifests/serviceaccount.yaml \
+            -f manifests/netpol.yaml
+
+      - name: Apply configs
+        run: |
+          kubectl apply -f manifests/controller/controller_config.yaml \
+            -f manifests/scheduler/scheduler_config.yaml \
+            -f manifests/scheduler/scheduler_secret.yaml
+
+      - name: Apply controller
+        run: |
+          kubectl apply -f testing/controller/controller_deployment.yaml
+          sleep 5
+
+      - name: Test label applied
+        run: |
+          if ! kubectl get pvc pvc1 -n anray-liu -o yaml | grep -q labels; then
+              echo "No labels found. Test failed."
+              exit 2
+          else
+              OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels -A 1)"
+              if [[ "${OUTPUT}" = *"volume-cleaner/unattached-time:"* ]]; then
+                  echo "Test passed."
+              else
+                  echo "Output: ${OUTPUT}"
+                  echo "Wrong label found. Test failed."
+                  exit 2
+              fi
+          fi
+
+      - name: Test label not applied
+        run: |
+          if ! kubectl get pvc pvc2 -n anray-liu -o yaml | grep -q labels; then
+              echo "Test passed."
+          else
+              OUTPUT="$(kubectl get pvc pvc2 -n anray-liu -o yaml | grep labels)"
+              echo "Output: ${OUTPUT}"
+              echo "Labels found. Test failed."
+              exit 2
+          fi
+
+      - name: Create stateful set
+        run: |
+          kubectl apply -f testing/sts.yaml
+          sleep 5
+
+      - name: Test label removed
+        run: |
+          if ! kubectl get pvc pvc1 -n anray-liu -o yaml | grep -q labels; then
+              echo "Test passed."
+          else
+              OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels)"
+              echo "Output: ${OUTPUT}"
+              echo "Labels found. Test failed."
+              exit 2
+          fi
+
+      - name: Delete stateful set
+        run: |
+          kubectl delete sts sts1 -n anray-liu
+          sleep 5
+
+      - name: Test label applied again
+        run: |
+          if ! kubectl get pvc pvc1 -n anray-liu -o yaml | grep -q labels; then
+              echo "No labels found. Test failed."
+              exit 2
+          else
+              OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels -A 1)"
+              if [[ "${OUTPUT}" = *"volume-cleaner/unattached-time:"* ]]; then
+                  echo "Test passed."
+              else
+                  echo "Output: ${OUTPUT}"
+                  echo "Wrong label found. Test failed."
+                  exit 2
+              fi
+          fi
+
+      - name: Apply scheduler
+        run: |
+          kubectl apply -f testing/scheduler/scheduler_job.yaml
+          sleep 5
+
+      - name: Test scheduler for pvc1
+        run: |
+          if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc1 from namespace anray-liu"; then
+              echo "Scheduler didn't find pvc1. Test failed."
+              exit 2
+          else
+              if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc1 from namespace anray-liu" -A 3 | grep "Grace period not passed."; then
+                  echo "Scheduler didn't skip pvc1. Test failed."
+                  exit 2
+              else
+                  echo "Test passed."
+              fi
+          fi
+
+      - name: Test scheduler for pvc2
+        run: |
+          if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc2 from namespace anray-liu"; then
+              echo "Scheduler didn't find pvc2. Test failed."
+              exit 2
+          else
+              if ! kubectl logs -l app=volume-cleaner-scheduler -n das | grep "Found pvc pvc2 from namespace anray-liu" -A 1 | grep "Not labelled. Skipping."; then
+                  echo "Scheduler didn't skip pvc2. Test failed."
+                  exit 2
+              else
+                  echo "Test passed."
+              fi
+          fi
+
+      # extra information
+      - name: Print logs
+        run: |
+          kubectl logs -l app=volume-cleaner-controller -n das
+          kubectl logs -l app=volume-cleaner-scheduler -n das
