feat(cicd): add many test cases

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -62,7 +62,7 @@ jobs:
           kubectl apply -f testing/scheduler/scheduler_job.yaml
           sleep 5
 
-      - name: Test labels applied
+      - name: Test label applied
         run: |
           OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels)"
           if [ "${OUTPUT}" = "" ]; then
@@ -79,6 +79,58 @@ jobs:
                   exit 2
               fi
           fi
+
+      - name: Test label not applied
+        run: |
+          OUTPUT="$(kubectl get pvc pvc2 -n anray-liu -o yaml | grep labels)"
+          if [ "${OUTPUT}" = "" ]; then
+              echo "Test passed."
+          else 
+              echo "${OUTPUT}"
+              echo "Labels found. Test failed."
+              exit 2
+          fi
+
+      - name: Create stateful set
+        run: |
+          kubectl apply -f testing/sts.yaml
+          sleep 5
+
+      - name: Test label removeed
+        run: |
+          OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels)"
+          if [ "${OUTPUT}" = "" ]; then
+              echo "Test passed."
+          else 
+              echo "${OUTPUT}"
+              echo "Labels found. Test failed."
+              exit 2
+          fi
+
+      - name: Delete stateful set
+        run: |
+          kubectl delete sts sts1 -n anray-liu
+          sleep 5
+
+      - name: Test label applied again
+        run: |
+          OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels)"
+          if [ "${OUTPUT}" = "" ]; then
+              echo "No labels found. Test failed."
+              exit 2
+          else 
+              echo "Test passed."
+              OUTPUT="$(kubectl get pvc pvc1 -n anray-liu -o yaml | grep labels -A 1)"
+              if [[ "${OUTPUT}" = *"volume-cleaner/unattached-time:"* ]]; then
+                  echo "Test passed."
+              else
+                  echo "${OUTPUT}"
+                  echo "Wrong label found. Test failed."
+                  exit 2
+              fi
+          fi
+
+
 
       - name: Print logs
         run: |
